// Wordle「例句挖空」提示(RS9 §2.2):每個答案一句簡單英文例句(答案位置為 _____)與中文意思。
// 自建內容(⛔ 非取自任何例句庫);覆蓋全部 ANSWERS,測試保證例句不洩漏答案。
export const HINTS = {
  actor: { en: 'The _____ won a prize for the movie.', zh: '演員' },
  adult: { en: 'Kids need an _____ with them at the pool.', zh: '成年人' },
  agree: { en: 'I _____ with you; it is a good idea.', zh: '同意' },
  album: { en: 'She put all her photos in a big _____.', zh: '相簿;專輯' },
  alive: { en: 'The fish is still _____ and swimming.', zh: '活著的' },
  allow: { en: 'My mom does not _____ phones at dinner.', zh: '允許' },
  alone: { en: 'He likes to walk _____ in the park.', zh: '獨自' },
  angle: { en: 'Turn the camera to get a better _____.', zh: '角度' },
  angry: { en: 'Dad was _____ when I broke the window.', zh: '生氣的' },
  apple: { en: 'I eat an _____ every day.', zh: '蘋果' },
  apply: { en: 'You can _____ for the job online.', zh: '申請;塗抹' },
  argue: { en: 'My brother and I _____ about the TV.', zh: '爭論' },
  audio: { en: 'The video has no _____, so I hear nothing.', zh: '音訊;聲音' },
  award: { en: 'She got an _____ for her great work.', zh: '獎項' },
  aware: { en: 'Are you _____ that the shop is closed?', zh: '察覺到的' },
  awful: { en: 'The food tasted _____, so I stopped eating.', zh: '糟糕的' },
  basic: { en: 'This book teaches _____ math for kids.', zh: '基本的' },
  beach: { en: 'We built a sandcastle on the _____.', zh: '海灘' },
  begin: { en: 'The class will _____ at nine.', zh: '開始' },
  bench: { en: 'Grandpa sat on a _____ in the park.', zh: '長椅' },
  birth: { en: 'The date of his _____ is in May.', zh: '出生' },
  black: { en: 'The night sky was dark and _____.', zh: '黑色的' },
  blind: { en: 'The _____ man walks with a white cane.', zh: '失明的' },
  block: { en: 'A big truck will _____ the road.', zh: '擋住;街區' },
  board: { en: 'The teacher wrote on the _____.', zh: '板子;黑板' },
  boost: { en: 'A good breakfast can _____ your energy.', zh: '提升' },
  brain: { en: 'Your _____ helps you think and learn.', zh: '大腦' },
  brave: { en: 'The _____ firefighter saved the cat.', zh: '勇敢的' },
  bread: { en: 'I put butter on my _____.', zh: '麵包' },
  break: { en: 'Be careful, do not _____ the cup.', zh: '打破;休息' },
  brief: { en: 'He gave a short and _____ answer.', zh: '簡短的' },
  bring: { en: 'Please _____ your lunch to school.', zh: '帶來' },
  broad: { en: 'The river is wide and _____ here.', zh: '寬闊的' },
  brown: { en: 'The dog has soft _____ fur.', zh: '棕色的' },
  build: { en: 'Birds _____ nests in the trees.', zh: '建造' },
  bunch: { en: 'She bought a _____ of bananas.', zh: '一串;一束' },
  cable: { en: 'Plug the _____ into the TV.', zh: '電線' },
  candy: { en: 'Too much _____ is bad for your teeth.', zh: '糖果' },
  carry: { en: 'Can you help me _____ this box?', zh: '搬;攜帶' },
  catch: { en: 'Throw the ball and I will _____ it.', zh: '接住' },
  cause: { en: 'Heavy rain can _____ a flood.', zh: '造成;原因' },
  chain: { en: 'The bike _____ came off again.', zh: '鏈條' },
  chair: { en: 'Please sit on the _____.', zh: '椅子' },
  chart: { en: 'The _____ shows our sales each month.', zh: '圖表' },
  cheap: { en: 'This shirt was very _____, only one dollar.', zh: '便宜的' },
  check: { en: 'Please _____ your answers before you finish.', zh: '檢查' },
  chest: { en: 'He felt a pain in his _____.', zh: '胸口;箱子' },
  chief: { en: 'The fire _____ leads the team.', zh: '首長;主要的' },
  child: { en: 'Every _____ should go to school.', zh: '小孩' },
  civil: { en: 'Be _____ and polite to other people.', zh: '有禮的;公民的' },
  claim: { en: 'He went to the desk to _____ his lost bag.', zh: '聲稱;認領' },
  class: { en: 'Our _____ has twenty students.', zh: '班級;課' },
  clean: { en: 'Please keep your room _____.', zh: '乾淨的' },
  clear: { en: 'The water is so _____ I can see fish.', zh: '清澈的;清楚的' },
  clock: { en: 'The _____ on the wall says three.', zh: '時鐘' },
  close: { en: 'Please _____ the door when you leave.', zh: '關上;近的' },
  cloud: { en: 'A dark _____ covered the sun.', zh: '雲' },
  coach: { en: 'Our soccer _____ is very kind.', zh: '教練' },
  coast: { en: 'We drove along the _____ by the sea.', zh: '海岸' },
  color: { en: 'Blue is my favorite _____.', zh: '顏色' },
  count: { en: 'Can you _____ from one to ten?', zh: '數數' },
  cover: { en: 'Please _____ the pot with a lid.', zh: '蓋住' },
  craft: { en: 'We made a paper _____ in art lessons.', zh: '手工藝' },
  crowd: { en: 'A big _____ watched the game.', zh: '人群' },
  crown: { en: 'The king wore a gold _____.', zh: '王冠' },
  cycle: { en: 'We _____ to school every morning.', zh: '騎單車;循環' },
  daily: { en: 'I read the news _____.', zh: '每天的' },
  dance: { en: 'Let us _____ to the music.', zh: '跳舞' },
  delay: { en: 'The snow made a long _____ for the bus.', zh: '延誤' },
  depth: { en: 'The _____ of the pool is two meters.', zh: '深度' },
  dream: { en: 'I had a strange _____ last night.', zh: '夢' },
  dress: { en: 'She wore a red _____ to the party.', zh: '洋裝' },
  drink: { en: 'Please _____ some water.', zh: '喝;飲料' },
  drive: { en: 'My dad will _____ us to the zoo.', zh: '開車' },
  earth: { en: 'The _____ goes around the sun.', zh: '地球' },
  eight: { en: 'A spider has _____ legs.', zh: '八' },
  empty: { en: 'The box is _____; nothing is inside.', zh: '空的' },
  enjoy: { en: 'I _____ reading books on rainy days.', zh: '享受;喜歡' },
  enter: { en: 'Knock before you _____ the room.', zh: '進入' },
  equal: { en: 'Two plus two is _____ to four.', zh: '相等的' },
  error: { en: 'There is an _____ in my homework.', zh: '錯誤' },
  event: { en: 'The school sports _____ is on Friday.', zh: '活動' },
  exact: { en: 'Tell me the _____ time, please.', zh: '精確的' },
  extra: { en: 'I brought an _____ pencil for you.', zh: '額外的' },
  faith: { en: 'She has _____ in her friends.', zh: '信任;信仰' },
  fancy: { en: 'We ate at a _____ restaurant.', zh: '高級的;花俏的' },
  field: { en: 'Cows eat grass in the _____.', zh: '田野;場地' },
  fifty: { en: 'Twenty plus thirty is _____.', zh: '五十' },
  final: { en: 'This is the _____ test of the year.', zh: '最後的' },
  flash: { en: 'A _____ of lightning lit the sky.', zh: '閃光' },
  fleet: { en: 'A _____ of ships sailed into the bay.', zh: '船隊' },
  floor: { en: 'The toys are all over the _____.', zh: '地板;樓層' },
  focus: { en: 'Turn off the TV so you can _____.', zh: '專注' },
  force: { en: 'Do not _____ the door open.', zh: '強迫;力量' },
  frame: { en: 'Put the photo in a nice _____.', zh: '框' },
  fresh: { en: 'These eggs are _____ from the farm.', zh: '新鮮的' },
  front: { en: 'Sit in the _____ row to see better.', zh: '前面' },
  fruit: { en: 'Bananas and grapes are my favorite _____.', zh: '水果' },
  funny: { en: 'The clown was very _____.', zh: '好笑的' },
  ghost: { en: 'He dressed up as a _____ for Halloween.', zh: '鬼' },
  giant: { en: 'The _____ was taller than a house.', zh: '巨人;巨大的' },
  glass: { en: 'Pour the milk into a _____.', zh: '玻璃杯;玻璃' },
  grace: { en: 'She dances with _____ and style.', zh: '優雅' },
  grade: { en: 'I got a good _____ on my test.', zh: '成績;年級' },
  grand: { en: 'The hotel has a _____ hall.', zh: '宏偉的' },
  grass: { en: 'The _____ is green after the rain.', zh: '草' },
  great: { en: 'You did a _____ job!', zh: '很棒的' },
  green: { en: 'Leaves are _____ in spring.', zh: '綠色的' },
  group: { en: 'We worked in a _____ of four.', zh: '組;群' },
  guard: { en: 'A _____ stands at the gate.', zh: '警衛' },
  guess: { en: 'Can you _____ what is in the box?', zh: '猜' },
  guest: { en: 'We have a _____ for dinner tonight.', zh: '客人' },
  guide: { en: 'The tour _____ showed us the museum.', zh: '導遊;指南' },
  happy: { en: 'I feel _____ on my birthday.', zh: '快樂的' },
  heart: { en: 'Your _____ beats faster when you run.', zh: '心臟;心' },
  heavy: { en: 'This bag is too _____ to lift.', zh: '重的' },
  honey: { en: 'Bees make sweet _____.', zh: '蜂蜜' },
  horse: { en: 'She rides a white _____.', zh: '馬' },
  hotel: { en: 'We stayed at a _____ near the beach.', zh: '旅館' },
  house: { en: 'Our _____ has a red door.', zh: '房子' },
  human: { en: 'Every _____ needs food and water.', zh: '人類' },
  ideal: { en: 'Sunny weather is _____ for a picnic.', zh: '理想的' },
  image: { en: 'The _____ on the screen is clear.', zh: '影像' },
  index: { en: 'Look up the word in the _____ at the back.', zh: '索引' },
  inner: { en: 'The _____ part of the fruit is sweet.', zh: '內部的' },
  input: { en: 'Type your _____ into the box.', zh: '輸入' },
  issue: { en: 'We talked about the _____ at the meeting.', zh: '問題;議題' },
  judge: { en: 'The _____ listened to both sides.', zh: '法官;裁判' },
  juice: { en: 'I drink orange _____ every morning.', zh: '果汁' },
  knife: { en: 'Cut the bread with a _____.', zh: '刀子' },
  label: { en: 'Read the _____ on the bottle.', zh: '標籤' },
  large: { en: 'An elephant is a very _____ animal.', zh: '大的' },
  laugh: { en: 'The joke made everyone _____.', zh: '笑' },
  layer: { en: 'The cake has a _____ of cream.', zh: '層' },
  learn: { en: 'We _____ new words every day.', zh: '學習' },
  level: { en: 'You reached the next _____ of the game.', zh: '等級;水平' },
  light: { en: 'Turn on the _____, it is dark.', zh: '燈;光' },
  limit: { en: 'The speed _____ here is fifty.', zh: '限制' },
  local: { en: 'We shop at the _____ market.', zh: '當地的' },
  logic: { en: 'Use _____ to solve the puzzle.', zh: '邏輯' },
  loose: { en: 'My tooth is _____ and will fall out.', zh: '鬆的' },
  lucky: { en: 'You are _____ to win the prize.', zh: '幸運的' },
  lunch: { en: 'We eat _____ at noon.', zh: '午餐' },
  magic: { en: 'The man did a _____ trick with a coin.', zh: '魔術' },
  major: { en: 'Rice is a _____ food in Asia.', zh: '主要的' },
  march: { en: 'The band will _____ down the street.', zh: '行進;三月' },
  match: { en: 'We watched a tennis _____ on TV.', zh: '比賽;火柴' },
  mayor: { en: 'The _____ runs the city.', zh: '市長' },
  medal: { en: 'She won a gold _____ at the games.', zh: '獎牌' },
  metal: { en: 'The spoon is made of _____.', zh: '金屬' },
  minor: { en: 'It was only a _____ problem.', zh: '輕微的;次要的' },
  model: { en: 'He built a _____ plane.', zh: '模型' },
  money: { en: 'I save my _____ in a jar.', zh: '錢' },
  month: { en: 'January is the first _____ of the year.', zh: '月' },
  moral: { en: 'The _____ of the story is to be kind.', zh: '寓意;道德的' },
  motor: { en: 'The boat has a small _____.', zh: '馬達' },
  mouse: { en: 'The cat chased the _____.', zh: '老鼠;滑鼠' },
  mouth: { en: 'Open your _____ and say ah.', zh: '嘴巴' },
  movie: { en: 'We watched a fun _____ last night.', zh: '電影' },
  music: { en: 'I listen to _____ when I study.', zh: '音樂' },
  night: { en: 'The stars shine at _____.', zh: '夜晚' },
  noise: { en: 'The dog made a loud _____.', zh: '噪音' },
  north: { en: 'Birds fly _____ in the spring.', zh: '北方' },
  novel: { en: 'She is reading a long _____.', zh: '小說' },
  nurse: { en: 'The _____ gave me a shot.', zh: '護士' },
  ocean: { en: 'Whales swim in the _____.', zh: '海洋' },
  offer: { en: 'Can I _____ you a cup of tea?', zh: '提供' },
  order: { en: 'We want to _____ a pizza.', zh: '點餐;順序' },
  owner: { en: 'Who is the _____ of this dog?', zh: '主人' },
  paint: { en: 'Let us _____ the fence white.', zh: '油漆;畫' },
  panel: { en: 'A solar _____ turns sunlight into power.', zh: '面板' },
  paper: { en: 'Write your name on the _____.', zh: '紙' },
  party: { en: 'We had a _____ for her birthday.', zh: '派對' },
  peace: { en: 'The world needs _____, not war.', zh: '和平' },
  phone: { en: 'My _____ is ringing.', zh: '電話' },
  photo: { en: 'Let me take a _____ of you.', zh: '照片' },
  piano: { en: 'She plays the _____ every day.', zh: '鋼琴' },
  piece: { en: 'May I have a _____ of cake?', zh: '一塊;一片' },
  pilot: { en: 'The _____ flies the plane.', zh: '飛行員' },
  pitch: { en: 'The baseball player will _____ the ball.', zh: '投球;音高' },
  pizza: { en: 'We ate cheese _____ for dinner.', zh: '披薩' },
  place: { en: 'This park is a nice _____ to rest.', zh: '地方' },
  plain: { en: 'I like _____ rice with no sauce.', zh: '樸素的;原味的' },
  plane: { en: 'The _____ took off from the airport.', zh: '飛機' },
  plant: { en: 'Water the _____ every day.', zh: '植物' },
  plate: { en: 'Put the food on a _____.', zh: '盤子' },
  point: { en: 'Do not _____ at people.', zh: '指;分數' },
  power: { en: 'The storm cut off the _____.', zh: '電力;力量' },
  press: { en: 'Please _____ the red button.', zh: '按' },
  price: { en: 'The _____ of this book is ten dollars.', zh: '價格' },
  pride: { en: 'She looked at her work with _____.', zh: '驕傲' },
  prize: { en: 'He won first _____ in the race.', zh: '獎品' },
  proof: { en: 'Do you have _____ that you paid?', zh: '證據' },
  quick: { en: 'Take a _____ look at this.', zh: '快的' },
  quiet: { en: 'Please be _____ in the library.', zh: '安靜的' },
  radio: { en: 'We listen to the _____ in the car.', zh: '收音機' },
  raise: { en: 'Please _____ your hand to answer.', zh: '舉起' },
  range: { en: 'The store sells a wide _____ of toys.', zh: '範圍' },
  rapid: { en: 'The river has a _____ current.', zh: '快速的' },
  reach: { en: 'I cannot _____ the top shelf.', zh: '搆到;到達' },
  ready: { en: 'Are you _____ to go?', zh: '準備好的' },
  reply: { en: 'Please _____ to my email soon.', zh: '回覆' },
  right: { en: 'Turn _____ at the corner.', zh: '右邊;正確的' },
  river: { en: 'Ducks swim in the _____.', zh: '河' },
  rough: { en: 'The road is _____ and bumpy.', zh: '粗糙的' },
  round: { en: 'A ball is _____.', zh: '圓的' },
  route: { en: 'This bus _____ goes downtown.', zh: '路線' },
  royal: { en: 'The queen lives in a _____ palace.', zh: '皇家的' },
  rural: { en: 'They live in a _____ area with farms.', zh: '鄉村的' },
  sauce: { en: 'Pour tomato _____ on the pasta.', zh: '醬汁' },
  scale: { en: 'Stand on the _____ to check your weight.', zh: '秤;規模' },
  scene: { en: 'The last _____ of the movie was sad.', zh: '場景' },
  score: { en: 'What was the final _____ of the game?', zh: '分數' },
  sense: { en: 'Dogs have a strong _____ of smell.', zh: '感覺' },
  serve: { en: 'The waiter will _____ the soup.', zh: '端上;服務' },
  seven: { en: 'There are _____ days in a week.', zh: '七' },
  shape: { en: 'A circle is a round _____.', zh: '形狀' },
  share: { en: 'Please _____ your toys with your sister.', zh: '分享' },
  sharp: { en: 'Be careful, the knife is _____.', zh: '鋒利的' },
  shell: { en: 'I found a pretty _____ on the sand.', zh: '貝殼' },
  shirt: { en: 'He wore a blue _____ to school.', zh: '襯衫' },
  shock: { en: 'The news was a big _____ to us.', zh: '震驚' },
  short: { en: 'My little brother is very _____.', zh: '矮的;短的' },
  sight: { en: 'The sunset was a lovely _____.', zh: '景象;視力' },
  skill: { en: 'Reading is an important _____.', zh: '技能' },
  sleep: { en: 'I _____ eight hours every night.', zh: '睡覺' },
  slide: { en: 'Kids go down the _____ at the park.', zh: '溜滑梯' },
  small: { en: 'A mouse is a _____ animal.', zh: '小的' },
  smart: { en: 'She is a _____ student.', zh: '聰明的' },
  smile: { en: 'Her _____ makes everyone happy.', zh: '微笑' },
  smoke: { en: 'I see _____ coming from the fire.', zh: '煙' },
  solid: { en: 'Ice is water in its _____ form.', zh: '固體的;堅固的' },
  solve: { en: 'Can you _____ this math problem?', zh: '解決' },
  sound: { en: 'I heard a strange _____ outside.', zh: '聲音' },
  south: { en: 'Birds fly _____ for the winter.', zh: '南方' },
  space: { en: 'Astronauts travel into _____.', zh: '太空;空間' },
  speak: { en: 'Can you _____ more slowly?', zh: '說話' },
  speed: { en: 'The car went at high _____.', zh: '速度' },
  spend: { en: 'I _____ my weekends with family.', zh: '花費;度過' },
  sport: { en: 'Soccer is my favorite _____.', zh: '運動' },
  staff: { en: 'The hotel _____ are very helpful.', zh: '員工' },
  stage: { en: 'The singer walked onto the _____.', zh: '舞台' },
  stand: { en: 'Please _____ up when the teacher comes in.', zh: '站' },
  start: { en: 'The race will _____ soon.', zh: '開始' },
  steam: { en: 'Hot _____ rose from the pot.', zh: '蒸氣' },
  steel: { en: 'The bridge is made of _____.', zh: '鋼鐵' },
  stick: { en: 'The dog brought back a _____.', zh: '棍子' },
  stone: { en: 'He threw a _____ into the lake.', zh: '石頭' },
  storm: { en: 'The _____ brought heavy rain.', zh: '暴風雨' },
  story: { en: 'Mom read me a bedtime _____.', zh: '故事' },
  style: { en: 'I like your hair _____.', zh: '風格;樣式' },
  sugar: { en: 'Do you want _____ in your tea?', zh: '糖' },
  super: { en: 'That was a _____ fun day!', zh: '超級的' },
  sweet: { en: 'This cake is very _____.', zh: '甜的' },
  table: { en: 'Put the plates on the _____.', zh: '桌子' },
  taste: { en: 'This soup has a great _____.', zh: '味道' },
  teach: { en: 'Mr. Lin will _____ us math.', zh: '教' },
  thank: { en: 'I want to _____ you for your help.', zh: '感謝' },
  theme: { en: 'The _____ of the party is pirates.', zh: '主題' },
  thick: { en: 'The book is very _____.', zh: '厚的' },
  thing: { en: 'What is that _____ on the floor?', zh: '東西' },
  think: { en: 'Let me _____ about it.', zh: '想' },
  three: { en: 'A triangle has _____ sides.', zh: '三' },
  throw: { en: 'Please _____ the ball to me.', zh: '丟' },
  tiger: { en: 'The _____ has orange and black stripes.', zh: '老虎' },
  title: { en: 'What is the _____ of the book?', zh: '標題;書名' },
  today: { en: 'What day is it _____?', zh: '今天' },
  topic: { en: 'The _____ of my report is bees.', zh: '主題;題目' },
  total: { en: 'The _____ cost is twenty dollars.', zh: '總共的' },
  touch: { en: 'Do not _____ the hot stove.', zh: '摸' },
  tower: { en: 'We climbed to the top of the _____.', zh: '塔' },
  track: { en: 'The runners raced around the _____.', zh: '跑道;軌道' },
  trade: { en: 'Do you want to _____ cards with me?', zh: '交換;貿易' },
  train: { en: 'We took the _____ to the city.', zh: '火車' },
  treat: { en: 'Mom gave us a sweet _____.', zh: '款待;零食' },
  trend: { en: 'Short videos are a big _____ now.', zh: '趨勢' },
  trial: { en: 'The judge started the _____ today.', zh: '審判;試驗' },
  truck: { en: 'A big _____ carried the logs.', zh: '卡車' },
  trust: { en: 'You can _____ me with your secret.', zh: '信任' },
  truth: { en: 'Always tell the _____.', zh: '真相;實話' },
  uncle: { en: 'My _____ is my mom\'s brother.', zh: '叔叔;舅舅' },
  union: { en: 'The workers formed a _____.', zh: '工會;聯盟' },
  upper: { en: 'The books are on the _____ shelf.', zh: '上面的' },
  usual: { en: 'I woke up at the _____ time.', zh: '平常的' },
  valid: { en: 'Your ticket is _____ for one day.', zh: '有效的' },
  value: { en: 'This old coin has great _____.', zh: '價值' },
  video: { en: 'We made a short _____ for our class.', zh: '影片' },
  visit: { en: 'We will _____ Grandma this weekend.', zh: '拜訪' },
  vital: { en: 'Water is _____ for all living things.', zh: '極其重要的' },
  voice: { en: 'She has a lovely singing _____.', zh: '聲音;嗓音' },
  waste: { en: 'Do not _____ food.', zh: '浪費' },
  watch: { en: 'Let us _____ the game together.', zh: '看;手錶' },
  water: { en: 'Fish live in _____.', zh: '水' },
  wheel: { en: 'The car has a flat front _____.', zh: '輪子' },
  white: { en: 'Snow is cold and _____.', zh: '白色的' },
  world: { en: 'There are many countries in the _____.', zh: '世界' },
  worry: { en: 'Do not _____, everything will be fine.', zh: '擔心' },
  write: { en: 'Please _____ your name here.', zh: '寫' },
  young: { en: 'The puppy is still very _____.', zh: '年輕的;幼小的' },
  youth: { en: 'He played soccer in his _____.', zh: '青春;年少時期' },
};
