// Wordle 字庫(自建,⛔ 非官方答案清單)。全部小寫 5 字母,無專有名詞與冒犯字。
// ANSWERS:出題用的常見單字;ALLOWED:可接受的猜測(含 ANSWERS)。
// 來源:依英文詞頻挑常見 5 字母字,以字典過濾並人工剔除人名、地名、縮寫、冒犯字;ANSWERS 為人工挑選。
const split = (s) => s.trim().split(/\s+/);

export const ANSWERS = split(`
  actor adult agree album alive allow alone angle angry apple apply argue
  audio award aware awful basic beach begin bench birth black blind block
  board boost brain brave bread break brief bring broad brown build bunch
  cable candy carry catch cause chain chair chart cheap check chest chief
  child civil claim class clean clear clock close cloud coach coast color
  count cover craft crowd crown cycle daily dance delay depth dream dress
  drink drive earth eight empty enjoy enter equal error event exact extra
  faith fancy field fifty final flash fleet floor focus force frame fresh
  front fruit funny ghost giant glass grace grade grand grass great green
  group guard guess guest guide happy heart heavy honey horse hotel house
  human ideal image index inner input issue judge juice knife label large
  laugh layer learn level light limit local logic loose lucky lunch magic
  major march match mayor medal metal minor model money month moral motor
  mouse mouth movie music night noise north novel nurse ocean offer order
  owner paint panel paper party peace phone photo piano piece pilot pitch
  pizza place plain plane plant plate point power press price pride prize
  proof quick quiet radio raise range rapid reach ready reply right river
  rough round route royal rural sauce scale scene score sense serve seven
  shape share sharp shell shirt shock short sight skill sleep slide small
  smart smile smoke solid solve sound south space speak speed spend sport
  staff stage stand start steam steel stick stone storm story style sugar
  super sweet table taste teach thank theme thick thing think three throw
  tiger title today topic total touch tower track trade train treat trend
  trial truck trust truth uncle union upper usual valid value video visit
  vital voice waste watch water wheel white world worry write young youth
`);

export const ALLOWED = split(`
  abbey abbot abide abode abort about above abuse abyss aches acids acorn
  acres acted actor acute adapt added adept admin admit adobe adopt adore
  adult after again agent agile aging agony agree ahead aided aides aimed
  aired aisle alarm album alert algae alias alibi alien align alike alive
  alley allow alloy aloft alone along aloud alpha altar alter amaze amber
  amend amino among ample amuse angel anger angle angry angst anime ankle
  annex annoy apart apple apply apron aptly arbor areas arena argue arias
  arise armed armor aroma arose array arrow arson ashes aside asked aspen
  assay asset atlas atoms attic audio audit aunts autos avail avert avian
  avoid await awake award aware awful awoke axial azure babes backs bacon
  badge badly bagel baggy baked baker bands bangs banjo banks barge barns
  baron basal based bases basic basil basin basis batch bathe baths baton
  bayou beach beads beams beans beard bears beast beats beech beers begin
  begun beige being belle bells belly below belts bench bends berry berth
  beset bikes bills binds binge bingo birch birds birth bison bites black
  blade blame blanc bland blank blast blaze bleak bleed bleep blend bless
  blind blink bliss blitz block bloke blood bloom blown blows blues bluff
  blunt blush board boast boats bogus boils bolts bombs bonds bones bonus
  booed books boost booth boots booze bored borne bound bouts bowed bowel
  bowls boxed boxer brace braid brain brake brand brass brave bravo brawl
  bread break breed brent bribe brick bride brief bring brink brisk broad
  brock broke brood brook broom broth brown brows brunt brush brute bucks
  bucky buddy budge buggy build built bulbs bulge bulky bulls bully bumps
  bumpy bunch bunny burns burnt burst buses busts butch butte buyer cabin
  cable cache cadet cages cakes calls camel cameo camps canal candy canes
  canoe canon carat cards cared cares cargo carol carry carte carts carve
  cases caste casts catch cater cause caves cease cedar cello cells cents
  chain chair chalk champ chant chaos chaps charm chart chase chats cheap
  cheat check cheek cheer chefs chess chest chick chief child chili chill
  chime chips choir choke chops chord chore chose chuck chunk chute cider
  cigar circa cited cites civic civil claim clamp clams clans clash clasp
  class claws clean clear clerk click cliff climb cling clips clive cloak
  clock clone close cloth cloud clout clown clubs clues coach coast coats
  cobra cocky cocoa coded codes codex coils coins colon color colts combo
  combs comes comet comfy comic comma condo cones cooks coral cords cores
  corny corps costs couch cough could count coupe court cover crabs craft
  crane crank crash crate crave crawl craze crazy cream creed creek creep
  crept crest crews cried cries crime crisp croft crook crops cross crowd
  crown crows crude cruel crush crust crypt cubes cubic cuffs cults cured
  cures curls curly curry curse curve curvy cutie cycle daddy daily dairy
  daisy dance dandy dared dares darts dated dates dazed deals dealt death
  debit debts debut decay decks decor deeds deems defer deity delay delta
  delve demon demos denim dense depot depth derby desks deter detox devil
  diary diets digit diner dirty discs disks ditch ditto diver dives dizzy
  docks dodge dodgy doggy dogma doing dolls dolly donor doors doses doubt
  dough doves downs dowry dozen draft drags drain drake drama drank drawn
  draws dread dream dress dried drier dries drift drill drink drive drone
  drops drove drown drugs drums drunk ducks ducts dudes dukes dummy dumps
  dunes duped dusty dwarf dwell dying eager eagle early earns earth eased
  eaten eater ebony edged edges edict edits eerie eight elbow elder elect
  elite elves email empty enact ended enemy enjoy enter entry envoy epoch
  equal equip erase erect error essay ether ethic ethos evade event every
  evils evoke exact exams excel exert exile exist exits expel extra fable
  faced faces facet facts faded fades fails faint fairs fairy faith faked
  fakes falls false famed fancy farce fared fares farms fatal fated fates
  fatty fault favor fears feast feats feces feeds feels felon fence feral
  ferns ferry fetal fetch fetus fever fiber fibre field fiend fiery fifth
  fifty fight filed files fills filly films filth final finch finds fined
  finer fines fired fires firms first firth fishy fists fives fixed fixes
  flags flair flake flame flank flaps flare flash flask flats flaws fleas
  fleet flesh flick flies fling flint flips flirt float flock flood floor
  flops flora floss flour flown flows fluff fluid fluke flung flush flute
  flyer focal focus foggy folds folio folks folly fonts foods fools footy
  force forge forks forms forte forth forts forty forum fouls found fours
  foxes foyer frail frame franc frank fraud freak freed frees fresh fried
  fries frogs front frost frown froze fruit fudge fuels fully fumes funds
  fungi funky funny furry fused fuzzy gabby gable gains games gamma gangs
  gases gated gates gator gauge gears geeks geese genes genie genre gents
  genus germs ghost giant giddy gifts girls girly given giver gives gland
  glare glass glaze glide globe gloom glory gloss glove glued gnome goals
  goats godly goers going golds goods goofy goons goose gorge gowns grabs
  grace grade graft grail grain grams grand grant grape graph grasp grass
  grate grave gravy great greed green greet grids grief grill grime grind
  grips groan groin groom gross group grove growl grown grows grunt guard
  guess guest guide guild guilt guise gully gusts habit hacks hails hairs
  hairy halal halls hands handy hanks happy hardy harem harms harsh haste
  hasty hatch hated hater hates haunt haven havoc hawks hazel heads heals
  heaps hears heart heath heats heavy hedge heels hefty heirs helix hello
  helps hence herbs herds heron hides highs hikes hills hilly hinge hints
  hippo hired hires hitch hives hoard hobby hoist holds holes holly homes
  honey honor hoods hooks hoops hoped hopes horde horns horse hosts hotel
  hound hours house hover howdy hubby human humid humor hunts hurry hurts
  husky hydro hymns hyped hyper icing icons ideal ideas idols image imply
  inbox incur index inept inert infer inked inlet inner input inter ionic
  irons irony isles issue itchy items ivory jacks jails jeans jelly jerks
  jerky jewel joins joint joked joker jokes jolly judge juice juicy jumbo
  jumps junta juror kappa karma kayak keeps kicks kills kilos kinds kings
  kinks kitty knack kneel knees knife knock knots known knows kraft kudos
  label labor laced laces lacks laden lager laird lakes lambs lamps lance
  lands lanes lapse large laser lasts latch later latex latte laugh lawns
  layer leach leads leafs leafy leaks leans leaps learn lease leash least
  leave ledge leech lefty legal legit lemon lends level lever liars libel
  licks lifts light liked likes lilac limbo limbs limit lined linen liner
  lines links lions lipid lists liter lived liver lives loads loans lobby
  lobes local locks locus lodge lofty logic login logos looks looms loops
  loose lords lorry loser loses lotto lotus lousy loved lover loves lower
  lowly loyal lucid lucky lumen lumps lunar lunch lungs lupus lured lying
  lymph lyric macho macro madam madly magic magma maids mails mains maize
  major maker makes males malls mamma manga mango mania manic manly manor
  maple march marks marry marsh masks mason masse match mater mates maths
  matte maxim maybe mayor meals means meant meats medal media medic meets
  melee melon melts memes menus merch mercy merge merit merry messy metal
  meter micro midst might miles milky mills mimic minds mined miner mines
  minor minus misty mixed mixer mixes moans modal model modem modes moist
  molds mommy money monks monte month moods moody moons moors moose moral
  morse motel moths motif motor motto mould mound mount mourn mouse mouth
  moved mover moves movie mower mucus muddy mules mummy munch mural murky
  music muted myths nails naive naked named names nanny nasal nasty natal
  naval necks needs needy nerve nests never newly nexus niche niece nifty
  night ninth nitro noble nodes noise noisy norms north nosed noses notch
  noted notes nouns novel nudge nukes nurse nutty nylon oasis obese occur
  ocean oddly offer often oiled older olive omega onion onset opens opera
  opium opted optic orbit order organ other otter ought ounce outer ovens
  overs overt owing owned owner oxide ozone paced paces packs paddy padre
  pagan pages pains paint pairs palms palsy panda panel panic pants papal
  paper parks parry parts party pasha pasta paste patch paths patio patty
  pause paved payer peace peach peaks pearl pears pedal peeps peers penal
  pence penny perch peril perks pesky pesos pests petty phase phone phony
  photo piano picks picky piece piers piety piggy piled piles pills pilot
  pinch pines pinky pinto pints pious piper pipes pitch pivot pixie pizza
  place plaid plain plane plank plans plant plate plays plaza plead pleas
  plots pluck plugs plume plump plush poems poets point poked poker polar
  poles polio polka polls ponds pools poppy porch pores ports posed poses
  posse posts potty pouch pound pours power prank prays press price pride
  prima prime print prior prism privy prize probe prone proof props prose
  proto prove proxy psalm psych puffy pulls pulse pumps punch pupil puppy
  purge purse quail quake quasi queen query quest queue quick quiet quill
  quilt quirk quite quits quota quote rabbi rabid raced racer races racks
  radar radio raids rails rains rainy raise rally ramps ranch range ranks
  rants rapid rated rates ratio raven razor reach react reads ready realm
  rebel recap recon reefs reels refer regal reign reins relax relay relic
  remit remix renal renew rents repay repel reply reset resin rests reuse
  revel rhino rhyme rider rides ridge riffs rifle right rigid rings rinse
  riots risen rises risks risky rites rival river roach roads roast robes
  robin robot rocks rocky rodeo rogue roles rolls roofs rooms roots ropes
  roses rotor rouge rough round rouse route rover rowdy rower royal ruins
  ruled ruler rules rumor rural rusty saber sacks sadly sails saint salad
  sales sally salon salts salty samba sands sandy sassy satin sauce sauna
  saved saver saves savvy scale scalp scams scans scant scare scarf scars
  scary scene scent scoop scope score scorn scout scrap screw scrub scrum
  seals seams seats sects sedan seeds seeks seems seine seize sells sends
  sense serge serum serve setup seven sever sewer shack shade shady shaft
  shake shaky shale shall shalt shame shape share shark sharp shave shawl
  shear sheds sheen sheep sheer sheet sheik shelf shell shift shine shiny
  ships shire shirt shock shoes shone shook shoot shops shore short shots
  shout shove shown shows shred shrub shrug shuts sided sides siege sighs
  sight sigma signs silky silly since sings sinks sinus siren sites sixth
  sixty sized sizes skate skier skies skill skins skips skirt skull skunk
  slabs slack slain slams slang slant slaps slash slate sleek sleep slept
  slice slick slide slime sling slips sloan slope sloth slots slows slump
  slums smack small smart smash smear smell smile smoke smoky snack snail
  snake snaps snare sneak sniff snoop snowy snuck snuff soaps sober socks
  soggy soils solar soles solid solos solve sonar songs sonic sorry sorts
  souls sound soups south space spade spans spare spark spawn speak spear
  specs speed spell spelt spend spent spice spicy spies spike spill spine
  spins spire spite split spoil spoke spoof spoon sport spots spout spray
  spree spurs squad squat squid stack staff stage stain stair stake stale
  stalk stall stamp stand stare stark stars start stash state stats stays
  stead steak steal steam steel steep steer stems steps stern stick stiff
  still sting stink stint stock stoic stoke stole stomp stone stony stood
  stool stoop stops store storm story stout stove strap straw stray strip
  strut stuck studs study stuff stump stung stunt style suede sugar suing
  suite suits sully sunny super surge swamp swans swaps swarm swear sweat
  sweep sweet swell swept swift swine swing swipe swirl swoop sword swore
  sworn swung synod syrup table taboo tacky tails taken taker takes tales
  talks tally tango tanks taped taper tapes tarot tasks taste tasty taxed
  taxes taxis teach teams tears tease teens teeth tells tempo temps tempt
  tends tenor tense tenth tents terms tests texts thank theft their theme
  there these theta thick thief thigh thine thing think third thong thorn
  those three threw throw thugs thumb ticks tidal tides tiers tiger tight
  tiles timed timer times timid tired tires title toast today token tolls
  tombs tonal toned tones tonic tools tooth topic torch torso total totem
  touch tough tours towed towel tower towns toxic toxin trace track tract
  trade trail train trait traps trash trays tread treat trees trend triad
  trial tribe trick tried tries trips troll troop trope trout truce truck
  truly trunk truss trust truth tubes tufts tulip tummy tumor tuned tunes
  turbo turns tutor twain tweak tweed tweet twice twigs twins twist tying
  typed types tyres ultra uncle uncut under undue unfit union unite units
  unity until upper upset urban urged urges urine usage users usher usual
  utter vague valet valid valor value valve vapor vases vault vegan veins
  venom vents venue verbs verge verse vests vicar video views vigil villa
  vines vinyl viola viper viral virus visas visit vista vital vivid vocal
  vodka vogue voice volts vomit voted voter votes vouch vowed vowel wacky
  wafer waged wager wages wagon waist waits waive wakes walks walls wally
  waltz wants wards wares warms warns wasps waste watch water watts waved
  waves wears weary weave weber wedge weeds weeks weigh weird wells whack
  whale wharf whats wheat wheel where which whiff while whine whips whisk
  white whole whoop whose widen widow width wield wight wills winds windy
  wines wings wiped wipes wired wires wiser witch witty wives woman woods
  woody words works world worms worry worse worst worth would wound woven
  wraps wrath wreck wrist write wrong wrote yacht yards years yeast yells
  yield young yours youth yummy zebra zoned zones
`);
